// Authentication actions
export const SET_CREDENTIALS = 'SET_CREDENTIALS'
export const SET_USER = 'SET_USER'

// Anecdotes actions
export const SET_ANECDOTES = 'SET_ANECDOTES'
export const SET_ANECDOTES_COUNT = 'SET_ANECDOTES_COUNT'
export const SET_ANECDOTES_LOADING = 'SET_ANECDOTES_IS_LOADING'
export const DELETE_ANECDOTE = 'DELETE_ANECDOTE'
export const SET_ANECDOTE_LOADING = 'SET_ANECDOTE_LOADING'
export const DECREMENT_ANECDOTES_COUNT = 'DECREMENT_ANECDOTES_COUNT'
export const INCREMENT_ANECDOTES_COUNT = 'INCREMENT_ANECDOTES_COUNT'
export const UPDATE_ANECDOTE = 'UPDATE_ANECDOTE'
export const ADD_ANECDOTE = 'ADD_ANECDOTE'

// Papers actions
export const SET_PAPERS = 'SET_PAPERS'
export const SET_PAPERS_COUNT = 'SET_PAPERS_COUNT'
export const SET_PAPERS_LOADING = 'SET_PAPERS_IS_LOADING'
export const DELETE_PAPER = 'DELETE_PAPER'
export const SET_PAPER_LOADING = 'SET_PAPER_LOADING'
export const DECREMENT_PAPERS_COUNT = 'DECREMENT_PAPERS_COUNT'
export const INCREMENT_PAPERS_COUNT = 'INCREMENT_PAPERS_COUNT'
export const UPDATE_PAPER = 'UPDATE_PAPER'
export const ADD_PAPER = 'ADD_PAPER'


// UI actions
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'
export const SET_AUTH_ERRORS = 'SET_AUTH_ERRORS'