// Authentication actions
export const SET_CREDENTIALS = 'SET_CREDENTIALS'
export const SET_USER = 'SET_USER'

// Anecdotes actions
export const SET_ANECDOTES = 'SET_ANECDOTES'
export const SET_ANECDOTES_COUNT = 'SET_ANECDOTES_COUNT'
export const SET_ANECDOTES_LOADING = 'SET_ANECDOTES_IS_LOADING'
export const DELETE_ANECDOTE = 'DELETE_ANECDOTE'
export const SET_ANECDOTE_LOADING = 'SET_ANECDOTE_LOADING'
export const DECREMENT_ANECDOTES_COUNT = 'DECREMENT_ANECDOTES_COUNT'

// UI actions
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'
export const SET_AUTH_ERRORS = 'SET_AUTH_ERRORS'